#!/usr/bin/perl -w

use DataManager;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (Name => "DataManager",
   ReceiveHandler => \&Receive);
$UNIVERSAL::datamanager = DataManager->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::datamanager->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::datamanager->Execute();
